Add bitmask checks for power- and thermometer
bpicode/fritzctl pull request #161
Opened 2018-07-09 17:02 UTC by jayme-github

Add helpers to check if device has built-in power- and/or thermometer

2018-07-09 17:13 UTC, jayme-github commented
Travis error looks a little like hyperactive `vet`.

2018-07-09 19:57 UTC, bpicode requested changes
Suggested to rename methods. See also #122.

2018-07-09 19:57 UTC, bpicode commented on fritz/device.go
> +func (d *Device) HasPowermeter() bool {
Can you rename this to CanMeasurePower?

2018-07-09 19:57 UTC, bpicode commented on fritz/device.go
> +func (d *Device) HasThermometer() bool {
Can you rename this to CanMeasureTemp?

2018-07-09 20:00 UTC, bpicode commented
Thanks for taking the time to contribute! The code looks fine, I just would like to change the name of the methods, see #122, where similar functionality was proposed.

> Travis error looks a little like hyperactive vet.
Yes, we can ignore that for now, it was built on beta version of go1.11.

2018-07-10 07:31 UTC, jayme-github commented
>  I just would like to change the name of the methods [...]

Sure, no problem. I must admit that I had not seen #122 before submitting this PR

2018-07-10 20:43 UTC, merged